name: Run CD Pipeline

# Only trigger, when the build workflow succeeded i.e. CI Pipeline
on:
  workflow_run:
    workflows: ["Push a Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        env: 
          DOCKER_USER: ${{ secrets.GK_DOCKER_NAME }}
        run: sudo docker pull $DOCKER_USER/bank:latest1
    
      - name: Delete Old Docker Container
        run: sudo docker rm -f bank_fastapi_container1 || true
    
      - name: Run Docker Container
        env: 
          DOCKER_USER: ${{ secrets.GK_DOCKER_NAME }}
        run: sudo docker run -it -d -p 8000:8000 --name bank_fastapi_container1 $DOCKER_USER/bank:latest1
