name: Push a Docker Image
# Only trigger, when the build workflow succeeded i.e. CI Pipeline
on:
  workflow_run:
    workflows: ["Run train and test"]
    types:
      - completed

jobs:
  train:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10 for bike project
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Train and save pipeline
      run: python train.py
    - uses: actions/upload-artifact@v2
      with:
        name: classify
        path: ./*.pkl
        retention-days: 1

  test:
    needs: train
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - uses: actions/download-artifact@v2
      with:
        name: classify
        path: .
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Test with pytest
      run: pytest

 
  push-image:
    needs: [train, test]
    runs-on: ubuntu-latest
    steps:
    - name: Repo Checkout
      uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: classify
        path: .

    - name: Login to Docker hub
      env:
        DOCKER_USER: ${{ secrets.GK_DOCKER_NAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS_TOKEN }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

    - name: Build the Docker image for Fastapi app
      env:
        DOCKER_USER: ${{ secrets.GK_DOCKER_NAME }}
      run: docker build . -f Dockerfile -t $DOCKER_USER/bank:latest1

    - name: Push the Docker Image
      env:
        DOCKER_USER: ${{ secrets.GK_DOCKER_NAME }}
      run: docker push $DOCKER_USER/bank:latest1

    - name: Logout to Docker hub
      run: docker logout
